# Form implementation generated from reading ui file '.\resource\aero.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtCore import *
from PyQt6.QtGui import *
from PyQt6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.resize(640, 480)

        self.centralwidget = QWidget(MainWindow)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())

        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("background-color: #ffffff;")

        self.mainLayout = QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(-1, 10, -1, -1)

        self.pushButton = QPushButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("border-color: white;\n"
"border-radius: 0px;")
        self.pushButton.setText("")
        icon = QIcon()
        icon.addPixmap(QPixmap(".\\resource\\system-file-manager.svg"), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QSize(100, 100))
        self.pushButton.setObjectName("pushButton")
        self.mainLayout.addWidget(self.pushButton)

        self.label = QLabel(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)

        font = QFont()
        font.setFamily("Inter")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)

        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        # self.label.setObjectName("label")
        self.mainLayout.addWidget(self.label)
        self.label_2 = QLabel(self.centralwidget)

        font = QFont()
        font.setFamily("Inter")
        font.setPointSize(10)

        self.label_2.setFont(font)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")
        self.mainLayout.addWidget(self.label_2)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(60, 20, 60, 10)
        self.horizontalLayout.setSpacing(50)
        # self.horizontalLayout.setObjectName("horizontalLayout")

        self.organizeButton = QToolButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.organizeButton.sizePolicy().hasHeightForWidth())
        self.organizeButton.setSizePolicy(sizePolicy)
        self.organizeButton.setBaseSize(QSize(0, 0))

        font = QFont()
        font.setFamily("STXinwei")
        font.setPointSize(15)
        self.organizeButton.setFont(font)
        self.organizeButton.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.organizeButton.setStyleSheet("#organizeButton {\n"
"    background-color: #43d6b5;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"    padding-top: 30%;\n"
"}\n"
"\n"
"#organizeButton:pressed {\n"
"    background-color: #28bca3;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"    padding-top: 30%;\n"
"}")
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(".\\resource\\start.svg"), QIcon.Mode.Normal, QIcon.State.Off)
        self.organizeButton.setIcon(icon1)
        self.organizeButton.setIconSize(QSize(100, 100))
        self.organizeButton.setCheckable(False)
        self.organizeButton.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.organizeButton.setAutoRaise(False)
        self.organizeButton.setArrowType(Qt.ArrowType.NoArrow)
        self.organizeButton.setObjectName("organizeButton")
        self.horizontalLayout.addWidget(self.organizeButton)
        self.customizeButton = QToolButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customizeButton.sizePolicy().hasHeightForWidth())
        self.customizeButton.setSizePolicy(sizePolicy)
        font = QFont()
        font.setFamily("STXinwei")
        font.setPointSize(15)
        self.customizeButton.setFont(font)
        self.customizeButton.setStyleSheet("#customizeButton {\n"
"background-color: #9bdb4d;\n"
"border-radius: 30px;\n"
"color: white;\n"
"padding-top: 30%;\n"
"}\n"
"\n"
"#customizeButton:pressed {\n"
"background-color: #68b723;\n"
"border-radius: 30px;\n"
"color: white;\n"
"padding-top: 30%;\n"
"}")
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(".\\resource\\setting.svg"), QIcon.Mode.Normal, QIcon.State.Off)
        self.customizeButton.setIcon(icon2)
        self.customizeButton.setIconSize(QSize(100, 100))
        self.customizeButton.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.customizeButton.setObjectName("customizeButton")
        self.horizontalLayout.addWidget(self.customizeButton)
        self.mainLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.closeButton = QPushButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setMinimumSize(QSize(150, 50))
        font = QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("#closeButton {\n"
"    border: 1px solid #abacae;"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#closeButton:pressed {\n"
"    background-color: #abacae;\n"
"    border-radius: 10px;\n"
"}")
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton, 0,Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.showOutputButton =QPushButton(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showOutputButton.sizePolicy().hasHeightForWidth())
        self.showOutputButton.setSizePolicy(sizePolicy)
        self.showOutputButton.setMinimumSize(QSize(150, 50))
        font = QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.showOutputButton.setFont(font)
        self.showOutputButton.setObjectName("showOutputButton")
        self.showOutputButton.setStyleSheet("#showOutputButton {\n"
"    border: 1px solid #64baff;"
"    border-radius: 10px;\n"
"    background-color: #8cd5ff;"
"}\n"
"\n"
"#showOutputButton:pressed {\n"
"    background-color: #64baff;\n"
"    border-radius: 10px;\n"
"}")
        self.horizontalLayout_2.addWidget(self.showOutputButton, 0, Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignVCenter)
        self.mainLayout.addLayout(self.horizontalLayout_2)
        # self.useless.addLayout(self.mainLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome To Seiri"))
        self.label_2.setText(_translate("MainWindow", "Organize your files in a simple and pragmatic way, my favorite."))
        self.organizeButton.setText(_translate("MainWindow", "Organize Files"))
        self.customizeButton.setText(_translate("MainWindow", "Customize Directories"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
        self.showOutputButton.setText(_translate("MainWindow", "Output"))
